name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      # 1) Use Node >= 20.19 (Angular 20 requirement)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'

      # 2) Build Angular on the runner (not inside SWA/Oryx)
      - name: Install dependencies
        run: npm ci
      - name: Build Angular app
        run: npm run build

      # (optional) sanity check — see what was produced
      - name: List build output
        run: |
          echo "Contents of dist:"
          ls -la dist || true
          echo "index.html paths:"
          find dist -maxdepth 3 -type f -name index.html -print

      # 3) Deploy prebuilt artifacts — SKIP APP BUILD
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_SMOKE_0EDBDE40F }}
          action: "upload"
          app_location: "dist/online-loan-management-system-ui/browser"  # path that contains index.html
          skip_app_build: true
          api_location: ""  # no Functions API

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_SMOKE_0EDBDE40F }}
          action: "close"
